Ckan 2.9 Improved design for keyword texts
ongov/ckanext-ontario_theme pull request #286
Opened 2023-02-17 21:43 UTC by Alexandra-Green

## What this PR accomplishes

Implements new pattern for displaying the keywords & selected filters:

## Issue(s) addressed

- French keyword filter translations
- Moves filters to below search query text
- Selected words in search query text are now bold
- Adds the close (x) and functionality to each search bar (including home) across site
- Adjusts Dataset and Ministry pages search labels, translations, and placeholders according to Figma design
- Shortens long input text placeholders in mobile and tablet across the site
- Allows empty searches

## What needs review

- Each search bar should clear the input field on clicking the (x), regardless of if there is a search query or not
- long placeholders are shortened in mobile and tablet
- The correct words are bold in the search results text and all translations are correct
- filter pills are correctly translated and look fine in mobile
- search bars align with Figma design

Notes: 

- clicking the "datasets with data" filter does not currently show a pill. This filter is going to be removed with the dataset search page changes, but let me know if there should be a pill.
- I added the `odc-search.js` script, let me know if I should consolidate this into the `ontario-header.js` or leave as is.

2023-02-21 21:26 UTC, KatiRG reviewed
The pills are too large on mobile for long filter names:
![Screen Shot 2023-02-21 at 4 26 37 PM](https://user-images.githubusercontent.com/1254764/220462147-94df7080-a111-47a0-8a02-755dea09aff6.png)

2023-02-21 21:48 UTC, KatiRG commented on ckanext/ontario_theme/fanstatic/scripts/odc-search.js
> +(function () {
Can you add a brief comment about the purpose of this script?

2023-02-21 21:50 UTC, KatiRG commented
> I added the odc-search.js script, let me know if I should consolidate this into the ontario-header.js or leave as is.

It's fine to leave it as is

2023-02-21 22:11 UTC, KatiRG commented
> facet_list.html and search_form.html now use some of the same code to translate the filter pills, should I be putting this in a separate html file and calling it as a snippet?

Yes, that's a good idea to consolidate!

2023-02-22 21:03 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/group/index.html
> +    <form {% if form_id %}id="{{ form_id }}" {% endif %}class="search-form{% if no_bottom_border %} no-bottom-border{% endif %}" method="get" data-module="select-switch" novalidate>
why is `if form_id` condition here? Looks like this condition will always be true since `form_id` is set on line 26.

2023-02-22 21:04 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/group/index.html
> +    <form {% if form_id %}id="{{ form_id }}" {% endif %}class="search-form{% if no_bottom_border %} no-bottom-border{% endif %}" method="get" data-module="select-switch" novalidate>
where is `no-bottom-border` passed from?

2023-02-22 21:05 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/group/read.html
> +  {% snippet 'snippets/search_form.html', form_id=form_id, type='dataset', query=q, sorting=sorting, sorting_selected=sort_by_selected, count=page.item_count, facets=facets, placeholder=_('Search dat
same as comments above

2023-02-22 21:06 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/organization/index.html
> +      <form {% if form_id %}id="{{ form_id }}" {% endif %}class="search-form{% if no_bottom_border %} no-bottom-border{% endif %}" method="get" data-module="select-switch" novalidate>
same as above

2023-02-22 21:07 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/organization/read.html
> +  <form {% if form_id %}id="{{ form_id }}" {% endif %}class="search-form{% if no_bottom_border %} no-bottom-border{% endif %}" method="get" data-module="select-switch" novalidate>
same as above

2023-02-22 21:07 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/package/search.html
> +      <form {% if form_id %}id="{{ form_id }}" {% endif %}class="search-form{% if no_bottom_border %} no-bottom-border{% endif %}" method="get" data-module="select-switch" novalidate>
same as above

2023-02-22 21:20 UTC, KatiRG requested changes
After these changes and the pill design fixes, looks good for merge!

- [ ] Each search bar should clear the input field on clicking the (x), regardless of if there is a search query or not
- [ ] long placeholders are shortened in mobile and tablet
- [ ] The correct words are bold in the search results text and all translations are correct
- [ ] filter pills are correctly translated and look fine in mobile
- [ ] search bars align with Figma design


Regarding the "datasets with no data": it looks like removing this filter is not in our ticket queue yet, so I would format this filter same as the other keywords. It will be in the code base for a while until then, and it looks too unsettling if not formatted in the same way.

2023-02-23 18:38 UTC, Alexandra-Green commented
> Regarding the "datasets with no data": it looks like removing this filter is not in our ticket queue yet, so I would format this filter same as the other keywords. It will be in the code base for a while until then, and it looks too unsettling if not formatted in the same way.

In the Dataset search page changes, designers would like for us to `Reorganize the filter topics order according to the markup and remove all filter options with only 1 choice ` the "Datasets with data" filter won't ever have more than one option so it will be removed in that UI ticket

2023-02-24 22:41 UTC, KatiRG approved these changes

2023-02-28 19:44 UTC, merged