Fixes resource page showing "Data not available" instead of data table
ongov/ckanext-ontario_theme pull request #378
Opened 2023-07-11 14:45 UTC by Alexandra-Green

## Issue(s) addressed

- Fixes bug causing the resource page to only show "Data not available" for open datasets
- Fixes bug causing the edit resource button to not appear on resource page
- Bugs introduced by right hand styling PR

## What needs review

- All users can see the data table and right hand boxes on open datasets
- Non admin users only see "Data not available" when trying to access under review or restricted resources. 
- Admin users can edit resources

2023-07-11 16:45 UTC, KatiRG requested changes
Some format fixes are required on this file (`djlint ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html --check`).

2023-07-11 16:45 UTC, KatiRG commented on ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
>  {% set is_open = (pkg.access_level == 'open') %}
`is_open` is defined globally here but is not available to the blocks, so can be removed here.

2023-07-11 17:02 UTC, KatiRG requested changes
A non-admin user can still see dataset page descriptions for datasets that are marked as Under Review or Restricted, instead of "Data not available".

2023-07-11 21:32 UTC, Alexandra-Green commented
> Some format fixes are required on this file (`djlint ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html --check`).

Okay so I made some of the changes, but I had to revert the ones in the {% block primary %} because it was adding extra words and causing errors, but everything should be formatted correctly, I'll be working on the linter ticket to get the formatter working correctly.

2023-07-17 19:49 UTC, KatiRG approved these changes

2023-07-17 19:49 UTC, merged