Ckanext validation: remove schema upload UI component
ongov/ckanext-ontario_theme pull request #428
Opened 2023-10-24 19:25 UTC by KatiRG

## What this PR accomplishes
Removes the UI component for uploading own schema in the resource edit page

## Issue addressed
DATA-1346

## What needs review
- confirm that the schema upload component does not appear in the resource Edit page
- ckanext-validation still able to validate a new resource. Note:
    - don't test on existing resources, that's not implemented yet
    - recommended to test on a valid file. Uploading an invalid file will cause the 504 error (known bug)

2023-10-24 20:08 UTC, KatiRG commented on ckanext/ontario_theme/plugin.py
> +# def get_datastore_info(resource_id):
ignore this file

2023-10-25 14:53 UTC, Alexandra-Green requested changes

2023-10-25 14:53 UTC, Alexandra-Green commented on ckanext/ontario_theme/schemas/external/ontario_theme_dataset.json
> +      "preset": "resource_schema"
```suggestion
      "preset": "hidden_in_form"
```
If you use the "hidden_in_form" preset, you can remove `resource_schema.html` altogether and achieve the same results

2023-10-25 14:53 UTC, Alexandra-Green commented on ckanext/ontario_theme/templates/internal/scheming/form_snippets/resource_schema.html
> +{% import 'macros/form.html' as form %}
You can remove this file altogether with the `"hidden_in_form"` preset (see comment above)

2023-10-25 14:53 UTC, Alexandra-Green commented on ckanext/ontario_theme/templates/internal/scheming/package/resource_read.html
> +          <p>{{info}}</p>
Are these lines still required?

2023-10-25 16:06 UTC, Alexandra-Green approved these changes

2023-10-25 17:30 UTC, merged