[TASK]: Only display "Report an error" on Open datasets
ongov/ckanext-ontario_theme pull request #456
Opened 2023-12-07 22:39 UTC by KobikahChandran

### What this PR accomplishes
"Report an error with this data" banner only appears when the dataset is Open

### Issue(s) addressed
DATA-1348

### What needs review
If the dataset is Open, the banner is at the bottom of the page.
If the dataset is either Under Review or Restricted, the banner does not appear.

2023-12-08 19:50 UTC, aimalkhan commented
@Alexandra-Green is this PR dealing with just 1348? seems like there are commits from two different people in there.

2023-12-08 19:51 UTC, Alexandra-Green commented
@aimalkhan it's because it's going into main instead of develop. Can we change the default for merges to go into develop?

2023-12-11 15:29 UTC, Alexandra-Green requested changes

2023-12-11 15:29 UTC, Alexandra-Green commented on ckanext/ontario_theme/templates/internal/package/read.html
> +        {% if pkg.resources %}
If a dataset is not open but has a resource, the banner still shows up. Changing this line to something like `if pkg.resources and the package's "access_level" == open` will prevent the banner from showing up

2023-12-11 22:06 UTC, Alexandra-Green commented on ckanext/ontario_theme/templates/internal/package/read.html
> +        {% if pkg.resources ['access_level'] == 'open' %}
```suggestion
        {% if pkg.resources and pkg['access_level'] == 'open' %}
```

2023-12-12 18:31 UTC, Alexandra-Green approved these changes
Looks good!

2023-12-12 18:38 UTC, merged