[Task]: Delete Help page
ongov/ckanext-ontario_theme pull request #543
Opened 2024-03-22 13:40 UTC by KobikahChandran

## What this PR accomplishes
- Deletes Help page
- Deletes all references to the Help page from the About page

## Issue(s) addressed
- DATA-1341

## What needs review
- Help page is removed completely including from navigation
- All references to the Help page are removed
- Help page goes to 404 page and not 500

2024-03-22 18:21 UTC, Alexandra-Green requested changes
Can you remove the Colby help page and it's translations from the .po & .pot files as well?

2024-03-22 18:23 UTC, Alexandra-Green commented on ckanext/ontario_theme/plugin.py
>  def csv_dump():
Can you add an additional new line above line 184? So there are 2 new lines before `def csv_dump():`

2024-03-25 20:45 UTC, Alexandra-Green commented
@aimalkhan do we need to update the version # in the `setup.py`?

2024-03-26 14:50 UTC, aimalkhan commented
> @aimalkhan do we need to update the version # in the `setup.py`?

@KobikahChandran update it to 2.1.32 please.

2024-03-28 14:39 UTC, Alexandra-Green approved these changes

2024-03-28 14:40 UTC, merged