bugfix: add extras dict to url
ongov/ckanext-ontario_theme pull request #593
Opened 2024-08-07 19:07 UTC by KatiRG

## What this PR accomplishes
The `h.add_url_param()` function requires a dictionary with 3 elements: `id`, `group_type`, and `is_organization`. This PR adds those parameters in to the empty `extras` object which was causing an error when rendering the Datasets page from the admin panel of the Ministry page.

## What needs review
1. Go to Ministries page and pick a ministry
2. click the Edit button
3. click the Datasets tab. Verify that the page displays.

2024-08-07 20:51 UTC, aleeexgreeen requested changes
While this works to remove the error when loading the page, the dropdown does not work correctly (changing the dropdown, sort is added to URL but dropdown remains Name Ascending, consequently, Name Ascending is unable be selected as an option). Because this bug was in relation to the Sort By drop down, we should make sure the dropdown works as well.

To tackle both issues, I recommend creating a `bulk_process.html` in the organizations folder and extending it from ckan.  This will also simplify things because the only variable for the extras dict will be the org id, while `group_type` will always be` 'organization'` and `is_organization` will always be `true`, from this html page. 
Copy the `{% block search_form %}`, add 
```
{% if request['params'] and 'sort' in request['params'] %}
     {% set sort_by_selected = request.params['sort'] %}
{% else %}
     {% set sort_by_selected = "titles asc" %}
 {% endif %}
```
add the extras dictionary to the snippet and lastly, change `title_string` to `titles`

2024-08-09 19:43 UTC, KatiRG commented
@aleeexgreeen this works but when landing on the Datasets tab, the list is not actually sorted (and the URL has no sort params) even though the dropdown is defaulted to "Name Ascending":

<img width="999" alt="Screenshot 2024-08-09 at 15 41 24" src="https://github.com/user-attachments/assets/069dea2b-0696-48bb-8a6a-0254004188df">

2024-08-09 20:25 UTC, aleeexgreeen commented
> @aleeexgreeen this works but when landing on the Datasets tab, the list is not actually sorted (and the URL has no sort params) even though the dropdown is defaulted to "Name Ascending":
> <img alt="Screenshot 2024-08-09 at 15 41 24" width="999" src="https://private-user-images.githubusercontent.com/1254764/356734507-069dea2b-0696-48bb-8a6a-0254004188df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzUyMDUsIm5iZiI6MTcyMzIzNDkwNSwicGF0aCI6Ii8xMjU0NzY0LzM1NjczNDUwNy0wNjlkZWEyYi0wNjk2LTQ4YmItOGE2YS0wMjU0MDA0MTg4ZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjAyMTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUzMjg0NmYwNmE2M2RlNzg2ZmFmMDk3N2ZhYzQ1NjU3NzhlOTIxOTZiNmZmMmQxOTIxOTQyZWU1YmNjYTk5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vTysqZn_05XHTEUz2USLQVbkLv2fw9Bf0FdRwSfQZGA">

Good point! I honestly don't know how to fix it, but it is sorting by `score desc, metadata_modified desc` aka relevance, so a quick and easy way would to just add relevance as a sorting option and change the else statement to default to `score desc, metadata_modified desc` 🤣

2024-08-09 20:27 UTC, aleeexgreeen commented on ckanext/ontario_theme/templates/internal/organization/bulk_process.html
> +  {% set extras = {'id': c.page.items[0]['organization']['id']} %}
```suggestion
  {% set extras = {'id': group_dict.id} %}
```
Core ckan has this `group_dict.id` for the organization id handy that you can use.

2024-08-09 21:53 UTC, KatiRG commented
This is working now, although on my local the "Last modified" does not actually list the datasets in correct order. The parameters are correct in the url: `organization/bulk_process/agriculture-food-and-rural-affairs?q=&sort=data_modified+desc`

Can you check on your side?

2024-08-12 14:00 UTC, aleeexgreeen commented
> This is working now, although on my local the "Last modified" does not actually list the datasets in correct order. The parameters are correct in the url: `organization/bulk_process/agriculture-food-and-rural-affairs?q=&sort=data_modified+desc`
> 
> Can you check on your side?

Good catch, it should be `metadata_modified+desc`, you can change last modified to `(_('Last Modified'), 'metadata_modified desc')`

2024-08-12 20:38 UTC, aleeexgreeen approved these changes
Looks and works great!

2024-08-12 20:39 UTC, merged